extends RefCounted
## Explicit affix pool (docs/ARCHITECTURE.md §9.3). Compact specs expanded by build_affixes() into
## the schema {"id", "kind", "group", "slot_types", "weight", "tags", "two_handed_mult",
## "tiers": [{"tier", "ilvl", "name", "mods": [{"stat","op","min","max"[,"min2","max2"][,"decimals"]}]}]}.
## OWNER: items. Used by ItemDB (preload); no class_name on purpose.
##
## Filters: an affix can roll on a base if base.slot_type is in "slot_types" AND (when "tags" is
## non-empty) the base has at least one of those tags (every base is tagged with its slot type,
## category and e.g. "caster", "shield", "quiver", "armour_def"; see item_base_data.gd).
## "two_handed_mult" scales rolled values on two-handed bases (added damage, spell damage...).
## Local stats (local_*) only appear on weapons (damage/speed/crit) and armour pieces (defences).

const TIER_ILVLS: Array[int] = [1, 8, 16, 26, 38, 50]

const ALL_ARMOUR := ["helmet", "body", "gloves", "boots"]
const EVERYTHING := ["weapon", "offhand", "helmet", "body", "gloves", "boots", "ring", "amulet", "belt"]

const RES_VALUES := [[6, 11], [12, 17], [18, 23], [24, 29], [30, 35], [36, 42]]
const ATTR_VALUES := [[10, 14], [15, 19], [20, 24], [25, 29], [30, 34], [35, 40]]
const LOCAL_DEF_INC := [[11, 20], [21, 32], [33, 44], [45, 56], [57, 70], [71, 85]]
const AILMENT_VALUES := [[3, 5], [6, 8], [9, 11], [12, 14], [15, 17], [18, 20]]
const ELE_DMG_VALUES := [[8, 12], [13, 17], [18, 22], [23, 27], [28, 32], [33, 40]]

const SPECS := [
	# ============================================================== PREFIXES
	{"id": "max_life", "kind": "prefix", "stat": "max_life", "op": "flat", "weight": 120,
		"slot_types": ["offhand", "helmet", "body", "gloves", "boots", "ring", "amulet", "belt"],
		"names": ["Hale", "Healthy", "Sanguine", "Stalwart", "Robust", "Virile"],
		"values": [[10, 19], [20, 29], [30, 44], [45, 59], [60, 79], [80, 99]]},
	{"id": "max_mana", "kind": "prefix", "stat": "max_mana", "op": "flat", "weight": 80,
		"slot_types": EVERYTHING, "tags": ["caster", "helmet", "body", "gloves", "boots", "ring", "amulet", "belt"],
		"names": ["Beryl", "Cobalt", "Azure", "Sapphire", "Cerulean", "Zaffre"],
		"values": [[15, 24], [25, 34], [35, 44], [45, 54], [55, 64], [65, 75]]},
	{"id": "max_energy_shield", "kind": "prefix", "stat": "max_energy_shield", "op": "flat", "weight": 70,
		"slot_types": ["ring", "amulet", "belt"],
		"names": ["Warded", "Guarded", "Hallowed", "Blessed", "Consecrated", "Seraphic"],
		"values": [[5, 9], [10, 15], [16, 22], [23, 30], [31, 40], [41, 51]]},
	{"id": "belt_armour", "kind": "prefix", "stat": "armour", "op": "flat", "weight": 80,
		"slot_types": ["belt"],
		"names": ["Banded", "Riveted", "Bolstered", "Braced", "Ironclad", "Impregnable"],
		"values": [[20, 40], [41, 80], [81, 130], [131, 190], [191, 260], [261, 340]]},
	# ---- local defences (armour pieces, shields, foci)
	{"id": "local_armour", "kind": "prefix", "stat": "local_armour", "op": "flat", "weight": 100,
		"slot_types": ["offhand", "helmet", "body", "gloves", "boots"], "tags": ["armour_def"],
		"names": ["Lacquered", "Studded", "Ribbed", "Fortified", "Plated", "Carapaced"],
		"values": [[6, 12], [13, 25], [26, 45], [46, 70], [71, 100], [101, 140]]},
	{"id": "local_evasion", "kind": "prefix", "stat": "local_evasion", "op": "flat", "weight": 100,
		"slot_types": ["offhand", "helmet", "body", "gloves", "boots"], "tags": ["evasion_def"],
		"names": ["Agile", "Dancer's", "Acrobat's", "Fleet", "Blurred", "Phased"],
		"values": [[8, 15], [16, 30], [31, 55], [56, 85], [86, 120], [121, 165]]},
	{"id": "local_energy_shield", "kind": "prefix", "stat": "local_energy_shield", "op": "flat", "weight": 100,
		"slot_types": ["offhand", "helmet", "body", "gloves", "boots"], "tags": ["es_def"],
		"names": ["Shining", "Glimmering", "Glittering", "Glowing", "Radiating", "Pulsing"],
		"values": [[3, 6], [7, 12], [13, 20], [21, 30], [31, 42], [43, 56]]},
	{"id": "local_armour_inc", "kind": "prefix", "stat": "local_armour", "op": "inc", "weight": 100,
		"slot_types": ["offhand", "helmet", "body", "gloves", "boots"], "tags": ["armour_def"],
		"names": ["Reinforced", "Layered", "Lobstered", "Buttressed", "Thickened", "Girded"],
		"values": LOCAL_DEF_INC},
	{"id": "local_evasion_inc", "kind": "prefix", "stat": "local_evasion", "op": "inc", "weight": 100,
		"slot_types": ["offhand", "helmet", "body", "gloves", "boots"], "tags": ["evasion_def"],
		"names": ["Shade's", "Ghost's", "Spectre's", "Wraith's", "Phantasm's", "Nightmare's"],
		"values": LOCAL_DEF_INC},
	{"id": "local_energy_shield_inc", "kind": "prefix", "stat": "local_energy_shield", "op": "inc", "weight": 100,
		"slot_types": ["offhand", "helmet", "body", "gloves", "boots"], "tags": ["es_def"],
		"names": ["Protective", "Strong-Willed", "Resolute", "Fearless", "Dauntless", "Indomitable"],
		"values": LOCAL_DEF_INC},
	# ---- local weapon damage
	{"id": "local_physical_damage", "kind": "prefix", "stat": "local_physical_damage", "op": "inc", "weight": 100,
		"slot_types": ["weapon"],
		"names": ["Heavy", "Serrated", "Wicked", "Vicious", "Bloodthirsty", "Cruel"],
		"values": [[40, 49], [50, 64], [65, 84], [85, 109], [110, 134], [135, 170]]},
	{"id": "local_added_physical", "kind": "prefix", "stat": "local_added_physical", "op": "flat", "weight": 100,
		"slot_types": ["weapon"], "two_handed_mult": 1.7,
		"names": ["Glinting", "Burnished", "Polished", "Honed", "Gleaming", "Annealed"],
		"values": [[1, 3, 4, 7], [3, 5, 8, 12], [5, 8, 15, 21], [9, 13, 24, 33], [14, 19, 37, 50], [20, 27, 54, 72]]},
	{"id": "local_added_fire", "kind": "prefix", "stat": "local_added_fire", "op": "flat", "weight": 80,
		"slot_types": ["weapon"], "two_handed_mult": 1.7,
		"names": ["Heated", "Smouldering", "Smoking", "Burning", "Flaming", "Scorching"],
		"values": [[2, 4, 5, 8], [4, 7, 10, 15], [7, 11, 17, 25], [12, 17, 28, 38], [18, 25, 42, 57], [26, 35, 60, 80]]},
	{"id": "local_added_cold", "kind": "prefix", "stat": "local_added_cold", "op": "flat", "weight": 80,
		"slot_types": ["weapon"], "two_handed_mult": 1.7,
		"names": ["Frosted", "Chilled", "Icy", "Frigid", "Freezing", "Frozen"],
		"values": [[2, 3, 4, 7], [3, 6, 9, 13], [6, 10, 15, 22], [10, 15, 25, 34], [16, 22, 37, 50], [23, 31, 53, 71]]},
	{"id": "local_added_lightning", "kind": "prefix", "stat": "local_added_lightning", "op": "flat", "weight": 80,
		"slot_types": ["weapon"], "two_handed_mult": 1.7,
		"names": ["Humming", "Buzzing", "Snapping", "Crackling", "Sparking", "Arcing"],
		"values": [[1, 1, 6, 10], [1, 2, 13, 20], [1, 3, 24, 36], [2, 4, 38, 52], [3, 6, 58, 78], [4, 8, 85, 112]]},
	{"id": "local_added_chaos", "kind": "prefix", "stat": "local_added_chaos", "op": "flat", "weight": 40,
		"slot_types": ["weapon"], "two_handed_mult": 1.7,
		"names": ["Tainted", "Foul", "Vile", "Baneful", "Accursed", "Malevolent"],
		"values": [[1, 3, 4, 7], [3, 5, 8, 12], [5, 8, 13, 19], [8, 12, 20, 28], [12, 17, 30, 41], [18, 24, 44, 58]]},
	# ---- global added attack damage (gloves, rings, amulets, quivers)
	{"id": "added_physical_attack", "kind": "prefix", "stat": "added_physical_attack", "op": "flat", "weight": 80,
		"slot_types": ["gloves", "ring", "amulet", "offhand"], "tags": ["gloves", "ring", "amulet", "quiver"],
		"names": ["Glinting", "Burnished", "Polished", "Honed", "Gleaming", "Annealed"],
		"values": [[1, 1, 2, 3], [1, 2, 3, 5], [2, 4, 6, 9], [4, 6, 9, 14], [6, 9, 14, 20], [9, 12, 20, 28]]},
	{"id": "added_fire_attack", "kind": "prefix", "stat": "added_fire_attack", "op": "flat", "weight": 70,
		"slot_types": ["gloves", "ring", "amulet", "offhand"], "tags": ["gloves", "ring", "amulet", "quiver"],
		"names": ["Heated", "Smouldering", "Smoking", "Burning", "Flaming", "Scorching"],
		"values": [[1, 2, 3, 4], [2, 3, 5, 7], [3, 5, 8, 12], [5, 8, 13, 18], [8, 11, 19, 26], [11, 15, 27, 36]]},
	{"id": "added_cold_attack", "kind": "prefix", "stat": "added_cold_attack", "op": "flat", "weight": 70,
		"slot_types": ["gloves", "ring", "amulet", "offhand"], "tags": ["gloves", "ring", "amulet", "quiver"],
		"names": ["Frosted", "Chilled", "Icy", "Frigid", "Freezing", "Frozen"],
		"values": [[1, 2, 2, 4], [2, 3, 4, 6], [3, 5, 7, 10], [5, 7, 11, 16], [7, 10, 17, 23], [10, 13, 24, 32]]},
	{"id": "added_lightning_attack", "kind": "prefix", "stat": "added_lightning_attack", "op": "flat", "weight": 70,
		"slot_types": ["gloves", "ring", "amulet", "offhand"], "tags": ["gloves", "ring", "amulet", "quiver"],
		"names": ["Humming", "Buzzing", "Snapping", "Crackling", "Sparking", "Arcing"],
		"values": [[1, 1, 3, 6], [1, 1, 6, 11], [1, 2, 11, 18], [1, 3, 19, 28], [2, 4, 28, 40], [3, 5, 40, 56]]},
	{"id": "added_chaos_attack", "kind": "prefix", "stat": "added_chaos_attack", "op": "flat", "weight": 35,
		"slot_types": ["gloves", "ring", "amulet", "offhand"], "tags": ["gloves", "ring", "amulet", "quiver"],
		"names": ["Tainted", "Foul", "Vile", "Baneful", "Accursed", "Malevolent"],
		"values": [[1, 2, 2, 4], [2, 3, 4, 6], [3, 4, 6, 9], [4, 6, 10, 14], [6, 8, 15, 20], [8, 11, 20, 27]]},
	# ---- spell damage (wands, staves, daggers, foci, amulets)
	{"id": "added_fire_spell", "kind": "prefix", "stat": "added_fire_spell", "op": "flat", "weight": 70,
		"slot_types": ["weapon", "offhand", "amulet"], "tags": ["caster", "amulet"], "two_handed_mult": 1.5,
		"names": ["Kindling", "Searing", "Blistering", "Incendiary", "Pyroclastic", "Cataclysmic"],
		"values": [[1, 2, 3, 5], [2, 4, 6, 9], [4, 7, 10, 15], [7, 10, 16, 22], [10, 14, 23, 32], [14, 19, 33, 44]]},
	{"id": "added_cold_spell", "kind": "prefix", "stat": "added_cold_spell", "op": "flat", "weight": 70,
		"slot_types": ["weapon", "offhand", "amulet"], "tags": ["caster", "amulet"], "two_handed_mult": 1.5,
		"names": ["Chilling", "Numbing", "Bitter", "Biting", "Glacial", "Polar"],
		"values": [[1, 2, 3, 4], [2, 3, 5, 8], [4, 6, 9, 13], [6, 9, 14, 20], [9, 13, 21, 29], [13, 17, 30, 40]]},
	{"id": "added_lightning_spell", "kind": "prefix", "stat": "added_lightning_spell", "op": "flat", "weight": 70,
		"slot_types": ["weapon", "offhand", "amulet"], "tags": ["caster", "amulet"], "two_handed_mult": 1.5,
		"names": ["Static", "Charged", "Galvanic", "Voltaic", "Thunderous", "Tempestuous"],
		"values": [[1, 1, 5, 9], [1, 2, 10, 17], [1, 3, 18, 28], [2, 4, 29, 40], [3, 6, 41, 56], [4, 8, 57, 76]]},
	{"id": "added_chaos_spell", "kind": "prefix", "stat": "added_chaos_spell", "op": "flat", "weight": 35,
		"slot_types": ["weapon", "offhand", "amulet"], "tags": ["caster", "amulet"], "two_handed_mult": 1.5,
		"names": ["Dark", "Shadowy", "Umbral", "Abyssal", "Eldritch", "Void-Touched"],
		"values": [[1, 2, 2, 4], [2, 3, 5, 7], [3, 5, 8, 12], [5, 8, 13, 18], [8, 11, 18, 26], [11, 15, 26, 35]]},
	{"id": "spell_damage", "kind": "prefix", "stat": "spell_damage", "op": "inc", "weight": 90,
		"slot_types": ["weapon", "offhand", "amulet"], "tags": ["caster", "amulet"], "two_handed_mult": 1.5,
		"names": ["Apprentice's", "Adept's", "Scholar's", "Professor's", "Occultist's", "Incanter's"],
		"values": [[10, 19], [20, 29], [30, 39], [40, 49], [50, 59], [60, 74]]},
	{"id": "elemental_damage", "kind": "prefix", "stat": "elemental_damage", "op": "inc", "weight": 60,
		"slot_types": ["weapon", "offhand", "ring", "amulet"], "tags": ["caster", "ring", "amulet"], "two_handed_mult": 1.5,
		"names": ["Catalysing", "Infusing", "Empowering", "Unleashed", "Overpowering", "Devastating"],
		"values": [[5, 9], [10, 14], [15, 19], [20, 24], [25, 29], [30, 35]]},
	{"id": "fire_damage", "kind": "prefix", "stat": "fire_damage", "op": "inc", "weight": 60,
		"slot_types": ["weapon", "offhand", "ring", "amulet"], "tags": ["caster", "ring", "amulet"], "two_handed_mult": 1.5,
		"names": ["Kindled", "Ashen", "Cindered", "Blazing", "Infernal", "Volcanic"],
		"values": ELE_DMG_VALUES},
	{"id": "cold_damage", "kind": "prefix", "stat": "cold_damage", "op": "inc", "weight": 60,
		"slot_types": ["weapon", "offhand", "ring", "amulet"], "tags": ["caster", "ring", "amulet"], "two_handed_mult": 1.5,
		"names": ["Wintry", "Hailing", "Sleeting", "Glaciated", "Boreal", "Arctic"],
		"values": ELE_DMG_VALUES},
	{"id": "lightning_damage", "kind": "prefix", "stat": "lightning_damage", "op": "inc", "weight": 60,
		"slot_types": ["weapon", "offhand", "ring", "amulet"], "tags": ["caster", "ring", "amulet"], "two_handed_mult": 1.5,
		"names": ["Ionised", "Stormy", "Shocking", "Thundering", "Electrified", "Fulminating"],
		"values": ELE_DMG_VALUES},
	{"id": "projectile_damage", "kind": "prefix", "stat": "projectile_damage", "op": "inc", "weight": 80,
		"slot_types": ["offhand"], "tags": ["quiver"],
		"names": ["Fletcher's", "Sharpshooter's", "Marksman's", "Deadeye's", "Sniper's", "Hawkeye's"],
		"values": [[8, 12], [13, 17], [18, 22], [23, 27], [28, 32], [33, 38]]},
	# ---- utility
	{"id": "movement_speed", "kind": "prefix", "stat": "movement_speed", "op": "inc", "weight": 100,
		"slot_types": ["boots"],
		"names": ["Runner's", "Sprinter's", "Stallion's", "Gazelle's", "Cheetah's", "Hellion's"],
		"values": [[6, 9], [10, 14], [15, 19], [20, 24], [25, 27], [28, 30]]},
	{"id": "item_rarity", "kind": "prefix", "stat": "item_rarity", "op": "inc", "weight": 45,
		"slot_types": ["ring", "amulet", "helmet", "boots"],
		"names": ["Magpie's", "Pirate's", "Collector's", "Hoarder's", "Dragon's", "Treasure Hunter's"],
		"values": [[6, 10], [11, 14], [15, 18], [19, 22], [23, 26], [27, 30]]},

	# ============================================================== SUFFIXES
	{"id": "strength", "kind": "suffix", "stat": "strength", "op": "flat", "weight": 100,
		"slot_types": EVERYTHING,
		"names": ["of the Brute", "of the Wrestler", "of the Bear", "of the Lion", "of the Gorilla", "of the Titan"],
		"values": ATTR_VALUES},
	{"id": "dexterity", "kind": "suffix", "stat": "dexterity", "op": "flat", "weight": 100,
		"slot_types": ["weapon", "offhand", "helmet", "body", "gloves", "boots", "ring", "amulet"],
		"names": ["of the Mongoose", "of the Lynx", "of the Fox", "of the Falcon", "of the Panther", "of the Leopard"],
		"values": ATTR_VALUES},
	{"id": "intelligence", "kind": "suffix", "stat": "intelligence", "op": "flat", "weight": 100,
		"slot_types": ["weapon", "offhand", "helmet", "body", "gloves", "boots", "ring", "amulet"],
		"names": ["of the Pupil", "of the Student", "of the Prodigy", "of the Augur", "of the Philosopher", "of the Sage"],
		"values": ATTR_VALUES},
	{"id": "all_attributes", "kind": "suffix", "stat": "all_attributes", "op": "flat", "weight": 40,
		"slot_types": ["amulet"],
		"names": ["of the Clouds", "of the Sky", "of the Meteor", "of the Comet", "of the Heavens", "of the Galaxy"],
		"values": [[3, 5], [6, 8], [9, 11], [12, 14], [15, 17], [18, 20]]},
	{"id": "fire_resistance", "kind": "suffix", "stat": "fire_resistance", "op": "flat", "weight": 100,
		"slot_types": ["offhand", "helmet", "body", "gloves", "boots", "ring", "amulet", "belt"],
		"names": ["of the Whelpling", "of the Salamander", "of the Drake", "of the Kiln", "of the Furnace", "of the Volcano"],
		"values": RES_VALUES},
	{"id": "cold_resistance", "kind": "suffix", "stat": "cold_resistance", "op": "flat", "weight": 100,
		"slot_types": ["offhand", "helmet", "body", "gloves", "boots", "ring", "amulet", "belt"],
		"names": ["of the Seal", "of the Penguin", "of the Walrus", "of the Yeti", "of the Polar Bear", "of Deep Winter"],
		"values": RES_VALUES},
	{"id": "lightning_resistance", "kind": "suffix", "stat": "lightning_resistance", "op": "flat", "weight": 100,
		"slot_types": ["offhand", "helmet", "body", "gloves", "boots", "ring", "amulet", "belt"],
		"names": ["of the Cloud", "of the Squall", "of the Storm", "of the Thunderhead", "of the Tempest", "of the Maelstrom"],
		"values": RES_VALUES},
	{"id": "chaos_resistance", "kind": "suffix", "stat": "chaos_resistance", "op": "flat", "weight": 45,
		"slot_types": ["offhand", "helmet", "body", "gloves", "boots", "ring", "amulet", "belt"],
		"names": ["of the Lost", "of Banishment", "of Eviction", "of Expulsion", "of Exile", "of Purity"],
		"values": [[5, 10], [11, 15], [16, 20], [21, 25], [26, 30], [31, 35]]},
	{"id": "elemental_resistance", "kind": "suffix", "stat": "elemental_resistance", "op": "flat", "weight": 50,
		"slot_types": ["ring", "amulet"],
		"names": ["of the Crystal", "of the Prism", "of the Kaleidoscope", "of Variegation", "of the Rainbow", "of the Span"],
		"values": [[3, 5], [6, 8], [9, 11], [12, 14], [15, 16], [17, 18]]},
	{"id": "attack_speed", "kind": "suffix", "stat": "attack_speed", "op": "inc", "weight": 80,
		"slot_types": ["gloves", "ring", "offhand"], "tags": ["gloves", "ring", "quiver"],
		"names": ["of Skill", "of Ease", "of Mastery", "of Grandmastery", "of Renown", "of Acclaim"],
		"values": [[4, 6], [7, 8], [9, 10], [11, 12], [13, 14], [15, 16]]},
	{"id": "local_attack_speed", "kind": "suffix", "stat": "local_attack_speed", "op": "inc", "weight": 100,
		"slot_types": ["weapon"],
		"names": ["of Skill", "of Ease", "of Mastery", "of Grandmastery", "of Renown", "of Acclaim"],
		"values": [[5, 7], [8, 10], [11, 13], [14, 16], [17, 20], [21, 25]]},
	{"id": "cast_speed", "kind": "suffix", "stat": "cast_speed", "op": "inc", "weight": 80,
		"slot_types": ["weapon", "offhand", "ring", "amulet"], "tags": ["caster", "ring", "amulet"], "two_handed_mult": 1.5,
		"names": ["of Talent", "of Nimbleness", "of Expertise", "of Legerdemain", "of Prestidigitation", "of Sortilege"],
		"values": [[5, 8], [9, 12], [13, 16], [17, 20], [21, 24], [25, 28]]},
	{"id": "crit_chance", "kind": "suffix", "stat": "crit_chance", "op": "inc", "weight": 70,
		"slot_types": ["offhand", "ring", "amulet"], "tags": ["focus", "quiver", "ring", "amulet"],
		"names": ["of Menace", "of Havoc", "of Disaster", "of Calamity", "of Ruin", "of Unmaking"],
		"values": [[10, 14], [15, 19], [20, 24], [25, 29], [30, 34], [35, 38]]},
	{"id": "local_crit_chance", "kind": "suffix", "stat": "local_crit_chance", "op": "inc", "weight": 80,
		"slot_types": ["weapon"],
		"names": ["of Needling", "of Stinging", "of Piercing", "of Puncturing", "of Penetrating", "of Incision"],
		"values": [[10, 14], [15, 19], [20, 24], [25, 29], [30, 34], [35, 38]]},
	{"id": "crit_multiplier", "kind": "suffix", "stat": "crit_multiplier", "op": "flat", "weight": 70,
		"slot_types": ["weapon", "offhand", "amulet"], "tags": ["weapon", "focus", "quiver", "amulet"],
		"names": ["of Ire", "of Anger", "of Rage", "of Fury", "of Ferocity", "of Destruction"],
		"values": [[8, 12], [13, 17], [18, 22], [23, 27], [28, 32], [33, 38]]},
	{"id": "life_regen", "kind": "suffix", "stat": "life_regen", "op": "flat", "weight": 70,
		"slot_types": ["offhand", "helmet", "body", "gloves", "boots", "ring", "amulet", "belt"],
		"tags": ["shield", "helmet", "body", "gloves", "boots", "ring", "amulet", "belt"],
		"names": ["of the Newt", "of the Lizard", "of the Flatworm", "of the Starfish", "of the Hydra", "of the Troll"],
		"values": [[1, 2], [3, 5], [6, 9], [10, 14], [15, 20], [21, 28]]},
	{"id": "life_leech", "kind": "suffix", "stat": "life_leech", "op": "flat", "weight": 50, "decimals": 1,
		"slot_types": ["weapon", "gloves", "ring", "amulet"],
		"names": ["of the Parasite", "of the Leech", "of the Remora", "of the Lamprey", "of the Vampire", "of Vampirism"],
		"values": [[0.2, 0.4], [0.4, 0.6], [0.6, 0.8], [0.8, 1.0], [1.0, 1.2], [1.2, 1.5]]},
	{"id": "mana_leech", "kind": "suffix", "stat": "mana_leech", "op": "flat", "weight": 35, "decimals": 1,
		"slot_types": ["weapon", "gloves", "ring"],
		"names": ["of Thirst", "of Craving", "of Hunger", "of Desire", "of Yearning", "of Consumption"],
		"values": [[0.2, 0.3], [0.3, 0.5], [0.5, 0.7], [0.7, 0.9], [0.9, 1.1], [1.1, 1.3]]},
	{"id": "life_on_kill", "kind": "suffix", "stat": "life_on_kill", "op": "flat", "weight": 60,
		"slot_types": ["weapon", "gloves", "ring"],
		"names": ["of Success", "of Victory", "of Triumph", "of Conquest", "of Glory", "of Legend"],
		"values": [[2, 4], [5, 7], [8, 11], [12, 15], [16, 20], [21, 26]]},
	{"id": "mana_on_kill", "kind": "suffix", "stat": "mana_on_kill", "op": "flat", "weight": 50,
		"slot_types": ["weapon", "ring"],
		"names": ["of Absorption", "of Osmosis", "of Diffusion", "of Assimilation", "of Siphoning", "of Devouring"],
		"values": [[1, 2], [2, 3], [3, 4], [4, 5], [5, 6], [6, 8]]},
	{"id": "life_on_hit", "kind": "suffix", "stat": "life_on_hit", "op": "flat", "weight": 50,
		"slot_types": ["weapon", "gloves", "ring", "offhand"], "tags": ["weapon", "gloves", "ring", "quiver"],
		"names": ["of Mending", "of Rejuvenation", "of Restoration", "of Regrowth", "of Nourishment", "of Revival"],
		"values": [[1, 2], [2, 3], [3, 4], [4, 6], [6, 8], [8, 10]]},
	{"id": "mana_regen", "kind": "suffix", "stat": "mana_regen", "op": "inc", "weight": 70,
		"slot_types": ["weapon", "offhand", "helmet", "ring", "amulet"], "tags": ["caster", "shield", "helmet", "ring", "amulet"],
		"names": ["of Excitement", "of Joy", "of Elation", "of Bliss", "of Euphoria", "of Nirvana"],
		"values": [[10, 19], [20, 29], [30, 39], [40, 49], [50, 59], [60, 69]]},
	{"id": "projectile_speed", "kind": "suffix", "stat": "projectile_speed", "op": "inc", "weight": 70,
		"slot_types": ["weapon", "offhand"], "tags": ["bow", "crossbow", "wand", "quiver"],
		"names": ["of Flight", "of Propulsion", "of the Zephyr", "of the Gale", "of the Whirlwind", "of the Hurricane"],
		"values": [[10, 14], [15, 19], [20, 24], [25, 29], [30, 34], [35, 40]]},
	{"id": "area_of_effect", "kind": "suffix", "stat": "area_of_effect", "op": "inc", "weight": 60,
		"slot_types": ["amulet"],
		"names": ["of Reach", "of Expanse", "of Magnitude", "of Grandeur", "of Immensity", "of Vastness"],
		"values": [[4, 6], [7, 9], [10, 12], [13, 15], [16, 18], [19, 22]]},
	{"id": "ignite_chance", "kind": "suffix", "stat": "ignite_chance", "op": "flat", "weight": 45,
		"slot_types": ["weapon", "gloves"],
		"names": ["of Embers", "of Cinders", "of Coals", "of Immolation", "of Conflagration", "of the Pyre"],
		"values": AILMENT_VALUES},
	{"id": "freeze_chance", "kind": "suffix", "stat": "freeze_chance", "op": "flat", "weight": 45,
		"slot_types": ["weapon", "gloves"],
		"names": ["of Frost", "of Rime", "of Hoarfrost", "of Glaciation", "of the Glacier", "of Absolute Zero"],
		"values": AILMENT_VALUES},
	{"id": "shock_chance", "kind": "suffix", "stat": "shock_chance", "op": "flat", "weight": 45,
		"slot_types": ["weapon", "gloves"],
		"names": ["of Static", "of Sparks", "of Voltage", "of Discharge", "of Electrocution", "of the Thunderbolt"],
		"values": AILMENT_VALUES},
	{"id": "bleed_chance", "kind": "suffix", "stat": "bleed_chance", "op": "flat", "weight": 45,
		"slot_types": ["weapon", "gloves"],
		"names": ["of Laceration", "of Gashing", "of Haemorrhage", "of Rending", "of Flaying", "of Exsanguination"],
		"values": AILMENT_VALUES},
	{"id": "poison_chance", "kind": "suffix", "stat": "poison_chance", "op": "flat", "weight": 45,
		"slot_types": ["weapon", "gloves"],
		"names": ["of Venom", "of Toxins", "of Blight", "of Contagion", "of Virulence", "of the Plague"],
		"values": AILMENT_VALUES},
	{"id": "local_block", "kind": "suffix", "stat": "local_block", "op": "flat", "weight": 70,
		"slot_types": ["offhand"], "tags": ["shield"],
		"names": ["of Deflection", "of Warding", "of the Bastion", "of the Rampart", "of the Citadel", "of the Aegis"],
		"values": [[2, 3], [3, 4], [4, 5], [5, 6], [6, 7], [7, 8]]},
	{"id": "potion_effect", "kind": "suffix", "stat": "potion_effect", "op": "inc", "weight": 60,
		"slot_types": ["belt"],
		"names": ["of Sipping", "of Refreshment", "of Replenishment", "of the Apothecary", "of the Alchemist", "of Transmutation"],
		"values": [[5, 9], [10, 14], [15, 19], [20, 24], [25, 29], [30, 35]]},
	{"id": "gold_find", "kind": "suffix", "stat": "gold_find", "op": "inc", "weight": 40,
		"slot_types": ["gloves", "ring", "amulet", "belt"],
		"names": ["of Greed", "of Avarice", "of Coin", "of Riches", "of Fortune", "of Opulence"],
		"values": [[8, 12], [13, 17], [18, 22], [23, 27], [28, 32], [33, 40]]},
]


## Expand SPECS into full affix dictionaries keyed by id.
static func build_affixes() -> Dictionary:
	var out := {}
	for s: Dictionary in SPECS:
		var tiers: Array = []
		for i in 6:
			var v: Array = s["values"][i]
			var m := {"stat": s["stat"], "op": s["op"], "min": v[0], "max": v[1]}
			if v.size() >= 4:
				m["min2"] = v[2]
				m["max2"] = v[3]
			if s.has("decimals"):
				m["decimals"] = s["decimals"]
			tiers.append({"tier": i + 1, "ilvl": TIER_ILVLS[i], "name": s["names"][i], "mods": [m]})
		out[s["id"]] = {
			"id": s["id"],
			"kind": s["kind"],
			"group": s.get("group", s["id"]),
			"slot_types": (s["slot_types"] as Array).duplicate(),
			"tags": (s.get("tags", []) as Array).duplicate(),
			"weight": s.get("weight", 100),
			"two_handed_mult": s.get("two_handed_mult", 1.0),
			"tiers": tiers,
		}
	return out
