extends Node
## Autoload "TreeDB": the passive skill tree (loaded from res://data/passive_tree.json) and its
## allocation rules. OWNER: passive tree (wave 1). CONTRACT STUB — keep every public signature.
## See docs/ARCHITECTURE.md §10. The data is generated by tools/tree/gen_passive_tree.py.
##
## Node dictionary: {"id": int, "name": String, "type": "start"|"small"|"notable"|"keystone"|
##   "attribute", "x": float, "y": float, "mods": Array[mod dict], "links": Array[int],
##   "class": String (start nodes only), "group": String (cluster id, optional)}
## Additions (optional fields, always present after loading):
##   "region": "str"|"dex"|"int"|"str_dex"|"dex_int"|"int_str"|"centre" (for colouring),
##   "orbit": [cx, cy, r] on ring and wheel-rim nodes: a link between two nodes with the same
##            orbit may be drawn as an arc (get_link_arc); straight lines are valid too.
##
##   "key":    stable semantic key of the node (tools/tree/id_map.json keeps ids stable across
##             regenerations: get_id_by_key / get_node_key).
##
## Rules: the class start is always allocated and never stored in `allocated`; other class starts
## can't be allocated or passed through. Only allocated nodes CONNECTED to the class start count:
## nodes left disconnected (e.g. an outdated save) neither extend the frontier nor block refunds,
## and can always be refunded (clean-up). can_allocate, get_allocatable and find_path (a 1-step
## path) always agree; can_refund and get_refundable always agree. Every API takes/returns int ids.
## Allocation queries are cheap so UIs may call them every frame: one analysis per allocation
## (connected set, refundable set via a single articulation-point DFS, frontier) is cached by
## class + allocation size + hash (verified by content), and find_path caches its last answer.

const TREE_PATH := "res://data/passive_tree.json"
## Suggested drawing radius per node type, in tree units. The generator keeps every link at
## least this radius + 10 away from any other node, and node centres >= 60 apart.
const NODE_RADIUS := {"start": 38.0, "keystone": 32.0, "notable": 24.0, "small": 14.0, "attribute": 12.0}
const NODE_TYPES: Array[String] = ["start", "attribute", "small", "notable", "keystone"]
## Region ids ("centre" = the Convergence nexus) with display names and suggested colours.
const REGIONS: Array[String] = ["str", "dex", "int", "str_dex", "dex_int", "int_str", "centre"]
const REGION_NAMES := {
	"str": "Strength", "dex": "Dexterity", "int": "Intelligence", "str_dex": "Strength / Dexterity",
	"dex_int": "Dexterity / Intelligence", "int_str": "Intelligence / Strength", "centre": "Convergence",
}
const REGION_COLORS := {
	"str": Color(0.86, 0.3, 0.26), "dex": Color(0.36, 0.78, 0.36), "int": Color(0.38, 0.5, 0.96),
	"str_dex": Color(0.85, 0.65, 0.25), "dex_int": Color(0.3, 0.76, 0.8), "int_str": Color(0.76, 0.4, 0.86),
	"centre": Color(0.9, 0.88, 0.8),
}
const _GRID_CELL := 200.0
## Allocation analyses kept at once (the UI typically asks about 1-2 allocations per frame).
const _ANALYSIS_CACHE_SIZE := 8

## id -> node dictionary
var nodes: Dictionary = {}

var _adj: Dictionary = {}            # int -> Array[int]
var _starts: Dictionary = {}         # class id -> start node id
var _links: Array[Vector2i] = []     # every undirected link once (x < y)
var _bounds := Rect2()
var _grid: Dictionary = {}           # Vector2i cell -> Array[int]
var _by_key: Dictionary = {}         # stable key -> id
var _lines_cache: Dictionary = {}    # id -> PackedStringArray
var _warned: Dictionary = {}         # ids already warned about
var _path_key := ""
var _path_alloc: Array = []          # copy of the allocation behind _path_key (exact cache check)
var _path_value: Array = []
var _analysis_cache: Dictionary = {} # "class|size|hash" -> analysis (see _analyze)
var _load_attempted := false


func _ready() -> void:
	if not _load_attempted:
		load_tree()


## (Re)load the tree. Returns false (with a warning, never an error) if the file is missing or
## malformed; the tree is then empty and every query returns the "nothing" answer.
func load_tree(path: String = TREE_PATH) -> bool:
	_load_attempted = true
	_clear()
	if not FileAccess.file_exists(path):
		push_warning("TreeDB: %s not found; the passive tree is empty" % path)
		return false
	var json := JSON.new()
	if json.parse(FileAccess.get_file_as_string(path)) != OK:
		push_warning("TreeDB: %s is not valid JSON (line %d: %s)" % [path, json.get_error_line(), json.get_error_message()])
		return false
	var data: Variant = json.data
	if not (data is Dictionary) or not ((data as Dictionary).get("nodes") is Array):
		push_warning("TreeDB: %s is not a valid tree file" % path)
		return false
	for raw in (data as Dictionary)["nodes"]:
		if not (raw is Dictionary) or not (raw as Dictionary).has("id"):
			push_warning("TreeDB: skipping a malformed node entry")
			continue
		var n := _normalize_node(raw as Dictionary)
		nodes[int(n["id"])] = n
	_build_indices()
	return not nodes.is_empty()


func is_loaded() -> bool:
	return not nodes.is_empty()


## Named get_passive (not get_node) to avoid clashing with Node.get_node().
func get_passive(id: int) -> Dictionary:
	_ensure_loaded()
	return nodes.get(id, {})


func get_all_ids() -> Array:
	_ensure_loaded()
	return nodes.keys()


func get_neighbors(id: int) -> Array:
	_ensure_loaded()
	var out: Array = []
	out.assign(_adj.get(id, []))
	return out


## The start node of a class ("warrior", "ranger", "sorcerer").
func get_start_node(class_id: String) -> int:
	_ensure_loaded()
	return int(_starts.get(class_id, -1))


## True if `id` is unallocated and adjacent to the class start or to an allocated node that is
## CONNECTED to the start (allocated nodes cut off from the start don't extend the frontier).
## `allocated` excludes the start node. Agrees with get_allocatable and find_path.
func can_allocate(allocated: Array, id: int, class_id: String) -> bool:
	_ensure_loaded()
	if not _is_allocatable_node(id):
		return false
	var start := get_start_node(class_id)
	if start < 0:
		return false
	var a := _cached_analysis(allocated, class_id)
	if a.is_empty():
		# Not analysed yet: cheap checks first (already allocated, next to the start, or next to
		# no allocated node at all) so one-off calls rarely need the connected set.
		var near := {}
		var next_to_start := false
		for nb in _adj.get(id, []):
			if nb == start:
				next_to_start = true
			near[nb] = true
		var next_to_alloc := false
		for v in allocated:
			var n := int(v)
			if n == id:
				return false
			if near.has(n):
				next_to_alloc = true
		if next_to_start:
			return true
		if not next_to_alloc:
			return false
		a = _analyze(allocated, class_id)
	elif (a["set"] as Dictionary).has(id):
		return false
	# Adjacent to the start or to an allocated node connected to it.
	var connected: Dictionary = a["connected"]
	for nb in _adj.get(id, []):
		if connected.has(nb):
			return true
	return false


## True if `id` is allocated and removing it keeps every other allocated node connected to the
## class start. (Allocated nodes that were already disconnected before — e.g. from an outdated
## save — are ignored, so they can always be cleaned up.) Agrees with get_refundable.
func can_refund(allocated: Array, id: int, class_id: String) -> bool:
	_ensure_loaded()
	var a := _analyze(allocated, class_id)
	if a.is_empty():
		return false
	return (a["refundable"] as Dictionary).has(id)


## Shortest list of unallocated nodes to allocate (in order) to reach `id`; [] if unreachable or
## already allocated. The last element is `id`. The path starts next to the start or next to an
## allocated node connected to it, never passes allocated nodes (connected or not) or starts.
func find_path(allocated: Array, id: int, class_id: String) -> Array:
	_ensure_loaded()
	var key := "%s|%d|%d|%d" % [class_id, id, allocated.size(), allocated.hash()]
	if key == _path_key and _path_alloc == allocated:
		return _path_value.duplicate()
	var result := _find_path_uncached(allocated, id, class_id)
	_path_key = key
	_path_alloc = allocated.duplicate()
	_path_value = result
	return result.duplicate()


## All mods granted by the allocated nodes (start node mods included). Unknown ids are skipped
## with a warning (once per id). Returns copies: callers may modify them.
func get_mods(allocated: Array, class_id: String = "") -> Array:
	_ensure_loaded()
	var out: Array = []
	var start := get_start_node(class_id) if class_id != "" else -1
	if start >= 0:
		for m in nodes[start]["mods"]:
			out.append((m as Dictionary).duplicate())
	var seen := {}
	for raw in allocated:
		var id := int(raw)
		if seen.has(id):
			continue
		seen[id] = true
		var n: Dictionary = nodes.get(id, {})
		if n.is_empty():
			_warn_once(id, "TreeDB.get_mods: unknown passive id %d ignored" % id)
			continue
		if n["type"] == "start":
			continue
		for m in n["mods"]:
			out.append((m as Dictionary).duplicate())
	return out


## Tooltip lines for a node (StatDefs.describe_mods of its mods).
func get_node_lines(id: int) -> PackedStringArray:
	_ensure_loaded()
	if not nodes.has(id):
		return PackedStringArray()
	if not _lines_cache.has(id):
		_lines_cache[id] = StatDefs.describe_mods(nodes[id]["mods"])
	return _lines_cache[id]


## Bounding rectangle of all node positions (for the UI's initial zoom).
func get_bounds() -> Rect2:
	_ensure_loaded()
	return _bounds


# ------------------------------------------------------------------------------------------------
# Additions (not in the original stub)
# ------------------------------------------------------------------------------------------------

## Node centre in tree units (y down). Vector2.ZERO for unknown ids.
func get_node_position(id: int) -> Vector2:
	var n: Dictionary = get_passive(id)
	if n.is_empty():
		return Vector2.ZERO
	return Vector2(n["x"], n["y"])


## Suggested drawing radius of a node (NODE_RADIUS by type).
func get_node_radius(id: int) -> float:
	var n: Dictionary = get_passive(id)
	return float(NODE_RADIUS.get(n.get("type", "small"), 14.0))


func get_node_type(id: int) -> String:
	return str(get_passive(id).get("type", ""))


func get_region(id: int) -> String:
	return str(get_passive(id).get("region", ""))


func is_start(id: int) -> bool:
	return get_node_type(id) == "start"


## Class id of a start node ("" for other nodes).
func get_start_class(id: int) -> String:
	return str(get_passive(id).get("class", ""))


## Every undirected link once, as Vector2i(a, b) with a < b, sorted. The array is read-only.
func get_links() -> Array[Vector2i]:
	_ensure_loaded()
	return _links


## Arc for drawing the link a-b when both nodes lie on the same orbit (a ring or a wheel rim):
## {"centre": Vector2, "radius": float, "start_angle": float, "end_angle": float} (radians, the
## minor arc from a to b, ready for CanvasItem.draw_arc). {} means draw a straight line.
func get_link_arc(a: int, b: int) -> Dictionary:
	var na: Dictionary = get_passive(a)
	var nb: Dictionary = get_passive(b)
	if na.is_empty() or nb.is_empty() or not na.has("orbit") or not nb.has("orbit"):
		return {}
	var oa: Array = na["orbit"]
	var ob: Array = nb["orbit"]
	if oa.size() != 3 or ob.size() != 3:
		return {}
	for i in 3:
		if not is_equal_approx(float(oa[i]), float(ob[i])):
			return {}
	var c := Vector2(float(oa[0]), float(oa[1]))
	var ta := (Vector2(na["x"], na["y"]) - c).angle()
	var tb := (Vector2(nb["x"], nb["y"]) - c).angle()
	return {"centre": c, "radius": float(oa[2]), "start_angle": ta, "end_angle": ta + wrapf(tb - ta, -PI, PI)}


## Ids of every node of a type ("notable", "keystone", ...), sorted.
func get_ids_by_type(node_type: String) -> Array[int]:
	_ensure_loaded()
	var out: Array[int] = []
	for id in nodes:
		if nodes[id]["type"] == node_type:
			out.append(id)
	out.sort()
	return out


## Allocated nodes (plus nothing else) that are connected to the class start (BFS order).
func get_connected(allocated: Array, class_id: String) -> Array[int]:
	_ensure_loaded()
	var out: Array[int] = []
	var a := _analyze(allocated, class_id)
	if a.is_empty():
		return out
	for id in a["connected"]:
		if id != a["start"]:
			out.append(id)
	return out


## Cleans an allocation (e.g. from a save made with an older tree): drops unknown ids, starts,
## duplicates and nodes not connected to the class start. Keeps the original order.
func sanitize_allocation(allocated: Array, class_id: String) -> Array[int]:
	_ensure_loaded()
	var out: Array[int] = []
	var a := _analyze(allocated, class_id)
	if a.is_empty():
		return out
	var connected: Dictionary = a["connected"]
	var seen := {}
	for raw in allocated:
		var id := int(raw)
		if connected.has(id) and id != a["start"] and not seen.has(id):
			seen[id] = true
			out.append(id)
	return out


## Every node that can be allocated right now (the frontier of the allocated nodes connected to
## the class start), sorted. Exactly the nodes for which can_allocate is true.
func get_allocatable(allocated: Array, class_id: String) -> Array[int]:
	_ensure_loaded()
	var a := _analyze(allocated, class_id)
	if a.is_empty():
		var none: Array[int] = []
		return none
	if a["frontier"] == null:
		var out: Array[int] = []
		var alloc: Dictionary = a["set"]
		var seen := {}
		for s in a["connected"]:
			for nb in _adj.get(s, []):
				if seen.has(nb) or alloc.has(nb) or not _is_allocatable_node(nb):
					continue
				seen[nb] = true
				out.append(nb)
		out.sort()
		a["frontier"] = out
	return (a["frontier"] as Array[int]).duplicate()


## Every allocated node that can be refunded right now, sorted: the connected allocated nodes
## that are not articulation points of the allocation (one DFS from the start), plus allocated
## entries that are not connected to the start at all (clean-up). Exactly the nodes for which
## can_refund is true. Cached per allocation, so a UI may mark refundable nodes every frame.
func get_refundable(allocated: Array, class_id: String) -> Array[int]:
	_ensure_loaded()
	var a := _analyze(allocated, class_id)
	if a.is_empty():
		var none: Array[int] = []
		return none
	return (a["refundable_list"] as Array[int]).duplicate()


## Stable semantic key of a node (e.g. "notable:brute_force", "toxic_bloom:spur:3"); "" if unknown.
func get_node_key(id: int) -> String:
	return str(get_passive(id).get("key", ""))


## Id of the node with a stable key (see get_node_key); -1 if unknown.
func get_id_by_key(key: String) -> int:
	_ensure_loaded()
	return int(_by_key.get(key, -1))


## The node under `pos` (tree units): the nearest node whose centre is within its drawing
## radius + `slack`; -1 if none. Uses a spatial grid (cheap enough for per-frame hover).
func find_node_at(pos: Vector2, slack: float = 6.0) -> int:
	_ensure_loaded()
	var cell := Vector2i(floori(pos.x / _GRID_CELL), floori(pos.y / _GRID_CELL))
	var best := -1
	var best_d := INF
	for dx in range(-1, 2):
		for dy in range(-1, 2):
			for id in _grid.get(cell + Vector2i(dx, dy), []):
				var n: Dictionary = nodes[id]
				var d := pos.distance_to(Vector2(n["x"], n["y"]))
				var r: float = float(NODE_RADIUS.get(n["type"], 14.0)) + slack
				if d <= r and d < best_d:
					best_d = d
					best = id
	return best


## Ids of nodes whose centre lies inside `rect` grown by `margin` (for culling while drawing).
func get_nodes_in_rect(rect: Rect2, margin: float = 40.0) -> Array[int]:
	_ensure_loaded()
	var out: Array[int] = []
	var r := rect.grow(margin)
	var c0 := Vector2i(floori(r.position.x / _GRID_CELL), floori(r.position.y / _GRID_CELL))
	var c1 := Vector2i(floori(r.end.x / _GRID_CELL), floori(r.end.y / _GRID_CELL))
	for cx in range(c0.x, c1.x + 1):
		for cy in range(c0.y, c1.y + 1):
			for id in _grid.get(Vector2i(cx, cy), []):
				var n: Dictionary = nodes[id]
				if r.has_point(Vector2(n["x"], n["y"])):
					out.append(id)
	return out


## Case-insensitive search over node names and tooltip lines (for the tree's search box).
## Returns matching ids, sorted; [] for an empty query.
func search(text: String) -> Array[int]:
	_ensure_loaded()
	var out: Array[int] = []
	var q := text.strip_edges().to_lower()
	if q == "":
		return out
	for id in nodes:
		var n: Dictionary = nodes[id]
		var hit := str(n["name"]).to_lower().contains(q)
		if not hit:
			for line in get_node_lines(id):
				if line.to_lower().contains(q):
					hit = true
					break
		if hit:
			out.append(id)
	out.sort()
	return out


## Summary lines of everything the allocation grants (merged per stat), e.g. for a "stats from
## passives" list in the tree panel.
func get_allocated_lines(allocated: Array, class_id: String = "") -> PackedStringArray:
	return StatDefs.describe_mods(get_mods(allocated, class_id))


# ------------------------------------------------------------------------------------------------
# Internals
# ------------------------------------------------------------------------------------------------

func _ensure_loaded() -> void:
	if not _load_attempted:
		load_tree()


func _clear() -> void:
	nodes.clear()
	_adj.clear()
	_starts.clear()
	_links = []
	_grid.clear()
	_by_key.clear()
	_lines_cache.clear()
	_bounds = Rect2()
	_path_key = ""
	_path_alloc = []
	_path_value = []
	_analysis_cache.clear()


func _normalize_node(raw: Dictionary) -> Dictionary:
	var n := raw.duplicate(true)
	n["id"] = int(raw["id"])
	n["name"] = str(raw.get("name", ""))
	var t := str(raw.get("type", "small"))
	if not NODE_TYPES.has(t):
		push_warning("TreeDB: node %d has unknown type '%s' (treated as small)" % [n["id"], t])
		t = "small"
	n["type"] = t
	n["x"] = float(raw.get("x", 0.0))
	n["y"] = float(raw.get("y", 0.0))
	var links: Array[int] = []
	var raw_links: Variant = raw.get("links", [])
	if raw_links is Array:
		for l in raw_links:
			links.append(int(l))
	n["links"] = links
	var mods: Array = []
	var raw_mods: Variant = raw.get("mods", [])
	if raw_mods is Array:
		for m in raw_mods:
			if m is Dictionary and (m as Dictionary).has("stat"):
				var md := (m as Dictionary).duplicate()
				md["stat"] = str(md["stat"])
				md["op"] = str(md.get("op", "flat"))
				md["value"] = float(md.get("value", 0.0))
				if md.has("value2"):
					md["value2"] = float(md["value2"])
				mods.append(md)
	n["mods"] = mods
	n["group"] = str(raw.get("group", ""))
	n["region"] = str(raw.get("region", ""))
	n["key"] = str(raw.get("key", ""))
	if t == "start":
		n["class"] = str(raw.get("class", ""))
	return n


func _build_indices() -> void:
	# Adjacency: union of both directions, unknown ids dropped.
	for id in nodes:
		var adj: Array[int] = []
		_adj[id] = adj
	for id in nodes:
		for l in nodes[id]["links"]:
			if not nodes.has(l) or l == id:
				push_warning("TreeDB: node %d links to unknown node %d" % [id, l])
				continue
			if not (_adj[id] as Array).has(l):
				(_adj[id] as Array).append(l)
			if not (_adj[l] as Array).has(id):
				(_adj[l] as Array).append(id)
	var keys: Array = nodes.keys()
	keys.sort()
	var first := true
	for id in keys:
		var n: Dictionary = nodes[id]
		(_adj[id] as Array).sort()
		n["links"] = (_adj[id] as Array).duplicate()
		for l in _adj[id]:
			if id < l:
				_links.append(Vector2i(id, l))
		if n["type"] == "start" and n.get("class", "") != "":
			if _starts.has(n["class"]):
				push_warning("TreeDB: two start nodes for class %s" % n["class"])
			else:
				_starts[n["class"]] = id
		if n["key"] != "":
			if _by_key.has(n["key"]):
				push_warning("TreeDB: nodes %d and %d share the key %s" % [_by_key[n["key"]], id, n["key"]])
			else:
				_by_key[n["key"]] = id
		var p := Vector2(n["x"], n["y"])
		if first:
			_bounds = Rect2(p, Vector2.ZERO)
			first = false
		else:
			_bounds = _bounds.expand(p)
		var cell := Vector2i(floori(p.x / _GRID_CELL), floori(p.y / _GRID_CELL))
		if not _grid.has(cell):
			var bucket: Array[int] = []
			_grid[cell] = bucket
		(_grid[cell] as Array).append(id)
	_links.make_read_only()


func _is_allocatable_node(id: int) -> bool:
	return nodes.has(id) and nodes[id]["type"] != "start"


func _to_set(allocated: Array) -> Dictionary:
	var s := {}
	for v in allocated:
		s[int(v)] = true
	return s


## Start + every allocated node reachable from it through allocated nodes (BFS order). Other
## class starts are never passed, even if they appear in the allocation.
func _connected_set(alloc: Dictionary, start: int) -> Dictionary:
	var seen := {start: true}
	var queue: Array[int] = [start]
	var head := 0
	while head < queue.size():
		var cur := queue[head]
		head += 1
		for nb in _adj.get(cur, []):
			if not seen.has(nb) and alloc.has(nb) and _is_allocatable_node(nb):
				seen[nb] = true
				queue.append(nb)
	return seen


## The cached analysis of an allocation for a class ({} for an unknown class / empty tree):
##   "start": int, "set": allocated id set, "connected": start + connected allocated (BFS order),
##   "refundable": id set, "refundable_list": Array[int] sorted, "frontier": Array[int] or null
##   (filled lazily by get_allocatable). Cached by class + size + hash and verified by content
## (a stored copy), so callers may mutate their array between calls.
func _analyze(allocated: Array, class_id: String) -> Dictionary:
	var hit := _cached_analysis(allocated, class_id)
	if not hit.is_empty():
		return hit
	var start := get_start_node(class_id)
	if start < 0:
		return {}
	var key := _analysis_key(allocated, class_id)
	var alloc := _to_set(allocated)
	var connected := _connected_set(alloc, start)
	var cut := _articulation_points(connected, start)
	var refundable := {}
	var refundable_list: Array[int] = []
	for id in alloc:
		# Stray entries (the start itself, disconnected or unknown ids) can always be cleaned up.
		if id == start or not connected.has(id) or not cut.has(id):
			refundable[id] = true
			refundable_list.append(id)
	refundable_list.sort()
	var a := {
		"alloc": allocated.duplicate(), "start": start, "set": alloc, "connected": connected,
		"refundable": refundable, "refundable_list": refundable_list, "frontier": null,
	}
	if _analysis_cache.size() >= _ANALYSIS_CACHE_SIZE:
		_analysis_cache.clear()
	_analysis_cache[key] = a
	return a


## The cached analysis of this exact allocation, or {} (no work beyond hashing/comparing it).
func _cached_analysis(allocated: Array, class_id: String) -> Dictionary:
	var hit: Dictionary = _analysis_cache.get(_analysis_key(allocated, class_id), {})
	if not hit.is_empty() and hit["alloc"] == allocated:
		return hit
	return {}


func _analysis_key(allocated: Array, class_id: String) -> String:
	return "%s|%d|%d" % [class_id, allocated.size(), allocated.hash()]


## Articulation points of the subgraph induced by `members` (which contains `root`), for a DFS
## rooted at `root`: a non-root node v is one iff some DFS child c has low[c] >= disc[v], i.e.
## removing v cuts c's subtree off the root. The root itself is never reported. Iterative (no
## recursion depth limit), O(nodes + links) of the subgraph.
func _articulation_points(members: Dictionary, root: int) -> Dictionary:
	var cut := {}
	var disc := {root: 0}
	var low := {root: 0}
	var parent := {root: -1}
	var next_index := {root: 0}
	var stack: Array[int] = [root]
	var time := 1
	while not stack.is_empty():
		var v: int = stack[-1]
		var nbs: Array = _adj.get(v, [])
		var i: int = next_index[v]
		if i < nbs.size():
			next_index[v] = i + 1
			var w: int = nbs[i]
			if not members.has(w):
				continue
			if not disc.has(w):
				disc[w] = time
				low[w] = time
				time += 1
				parent[w] = v
				next_index[w] = 0
				stack.append(w)
			elif w != parent[v]:
				low[v] = mini(low[v], disc[w])
		else:
			stack.pop_back()
			var p: int = parent[v]
			if p >= 0:
				low[p] = mini(low[p], low[v])
				if p != root and low[v] >= disc[p]:
					cut[p] = true
	return cut


func _find_path_uncached(allocated: Array, id: int, class_id: String) -> Array:
	if not _is_allocatable_node(id):
		return []
	var a := _analyze(allocated, class_id)
	if a.is_empty():
		return []
	var alloc: Dictionary = a["set"]
	if alloc.has(id):
		return []
	var sources: Dictionary = a["connected"]
	var prev := {}
	var queue: Array[int] = []
	for s in sources:
		prev[s] = -1
		queue.append(s)
	var head := 0
	var found := false
	while head < queue.size():
		var cur := queue[head]
		head += 1
		if cur == id:
			found = true
			break
		for nb in _adj.get(cur, []):
			if prev.has(nb) or alloc.has(nb) or not _is_allocatable_node(nb):
				continue
			prev[nb] = cur
			queue.append(nb)
	if not found:
		return []
	var path: Array = []
	var c := id
	while not sources.has(c):
		path.push_front(c)
		c = prev[c]
	return path


func _warn_once(id: int, msg: String) -> void:
	if _warned.has(id):
		return
	_warned[id] = true
	push_warning(msg)
